"""
Compliance Rule Catalogue for GemmaFinOS.
Contains ~40 rules across various Indian financial frameworks (PMLA, FEMA, RBI KYC, GST,
Income Tax, Corporate Governance).
Each rule includes ideal_vector_target for cosine similarity scoring.
"""

from typing import Dict, Any, List

COMPLIANCE_RULES: List[Dict[str, Any]] = [
    # ═══════════════════════════════════════════════════════════════
    # AML (Anti-Money Laundering) — PMLA 2002 — 10 rules
    # ═══════════════════════════════════════════════════════════════
    {
        "id": 1,
        "code": "AML-001",
        "name": "Cash Transaction Reporting (CTR)",
        "framework": "PMLA",
        "description": "Any single cash transaction exceeding ₹10 lakh must be reported to FIU-IND within 7 days.",
        "severity": "high",
        "max_penalty_inr": 1_000_000,
        "penalty_per_day_inr": 10_000,
        "imprisonment_risk": False,
        "ideal_vector_target": {"monthly_txn_volume": 0.8, "cash_ratio": 0.9, "anomaly_risk_score": 0.6},
        "remediation_steps": ["File CTR with FIU-IND portal within 7 days", "Maintain transaction records for 5 years", "Train staff on cash handling thresholds"],
        "references": ["PMLA Section 12", "FIU-IND Circular 2023-04"],
    },
    {
        "id": 2,
        "code": "AML-002",
        "name": "Structuring / Smurfing Detection",
        "framework": "PMLA",
        "description": "Multiple cash transactions just below ₹10 lakh threshold to avoid CTR filing.",
        "severity": "critical",
        "max_penalty_inr": 10_000_000,
        "penalty_per_day_inr": 50_000,
        "imprisonment_risk": True,
        "imprisonment_months": 84,
        "ideal_vector_target": {"monthly_txn_volume": 0.9, "cash_ratio": 0.8, "anomaly_risk_score": 0.9},
        "remediation_steps": ["File STR immediately", "Flag account for enhanced monitoring", "Review all related accounts", "Consider filing with law enforcement"],
        "references": ["PMLA Section 3", "PMLA Section 4"],
    },
    {
        "id": 3,
        "code": "AML-003",
        "name": "Suspicious Transaction Reporting (STR)",
        "framework": "PMLA",
        "description": "Transactions exhibiting unusually complex patterns, large values, or unusual economic rationale must be reported as STR.",
        "severity": "high",
        "max_penalty_inr": 5_000_000,
        "penalty_per_day_inr": 25_000,
        "imprisonment_risk": True,
        "imprisonment_months": 7,
        "ideal_vector_target": {"avg_ticket_size": 0.8, "anomaly_risk_score": 0.9, "sector_risk_score": 0.7},
        "remediation_steps": ["File STR with FIU-IND within 7 working days", "Preserve transaction records", "Do not tip off the customer", "Review customer relationship"],
        "references": ["PMLA Section 12", "PMLA Rules 2013, Rule 8"],
    },
    {
        "id": 4,
        "code": "AML-004",
        "name": "Shell Company Indicators",
        "framework": "PMLA",
        "description": "High turnover entity with low employee count and single director — classic shell company pattern.",
        "severity": "critical",
        "max_penalty_inr": 50_000_000,
        "penalty_per_day_inr": 100_000,
        "imprisonment_risk": True,
        "imprisonment_months": 84,
        "ideal_vector_target": {"business_age_years": 0.1, "director_count": 0.1, "anomaly_risk_score": 0.8, "monthly_txn_volume": 0.7},
        "remediation_steps": ["Conduct enhanced due diligence", "Verify physical business presence", "Request audited financial statements", "Consider exiting the relationship"],
        "references": ["PMLA Section 12", "RBI Master Direction on KYC"],
    },
    {
        "id": 5,
        "code": "AML-005",
        "name": "Cross-Border Transaction Monitoring",
        "framework": "PMLA",
        "description": "International transactions without clear economic rationale or FEMA compliance.",
        "severity": "high",
        "max_penalty_inr": 3_000_000,
        "penalty_per_day_inr": 5_000,
        "imprisonment_risk": False,
        "ideal_vector_target": {"cross_border_ratio": 0.9, "anomaly_risk_score": 0.7, "avg_ticket_size": 0.6},
        "remediation_steps": ["Verify FEMA compliance for each cross-border transaction", "Obtain proper purpose codes", "File with RBI if required", "Review against sanctions lists"],
        "references": ["PMLA Section 12", "FEMA 1999, Section 5"],
    },
    {
        "id": 6,
        "code": "AML-006",
        "name": "Dormant Account Sudden Activity",
        "framework": "PMLA",
        "description": "Account inactive for over 6 months showing sudden high-volume transactions — red flag for money laundering.",
        "severity": "high",
        "max_penalty_inr": 2_000_000,
        "penalty_per_day_inr": 10_000,
        "imprisonment_risk": False,
        "ideal_vector_target": {"business_age_years": 0.5, "anomaly_risk_score": 0.8, "monthly_txn_volume": 0.6},
        "remediation_steps": ["Contact customer to understand reason for sudden activity", "Review source of funds", "Consider placing account under enhanced monitoring", "File STR if funds appear suspicious"],
        "references": ["PMLA Section 12", "FIU-IND Advisory on Dormant Accounts"],
    },
    {
        "id": 7,
        "code": "AML-007",
        "name": "Rapid Succession Transfers",
        "framework": "PMLA",
        "description": "More than 5 significant transfers within 24 hours with no economic rationale — potential layering.",
        "severity": "medium",
        "max_penalty_inr": 1_000_000,
        "penalty_per_day_inr": 5_000,
        "imprisonment_risk": False,
        "ideal_vector_target": {"monthly_txn_volume": 0.9, "anomaly_risk_score": 0.7, "avg_ticket_size": 0.5},
        "remediation_steps": ["Review transaction chain for round-trip patterns", "Check counterparty profiles", "File STR if layering confirmed"],
        "references": ["PMLA Section 3 (Money Laundering Offence)"],
    },
    {
        "id": 8,
        "code": "AML-008",
        "name": "High-Value Cash Deposit Reporting",
        "framework": "PMLA",
        "description": "Single cash deposit exceeding ₹50 lakh requires additional documentation and scrutiny.",
        "severity": "medium",
        "max_penalty_inr": 500_000,
        "penalty_per_day_inr": 2_000,
        "imprisonment_risk": False,
        "ideal_vector_target": {"cash_ratio": 0.8, "avg_ticket_size": 0.9, "anomaly_risk_score": 0.4},
        "remediation_steps": ["Obtain cash source documentation", "Verify PAN/Aadhaar of depositor", "Check against tax compliance records"],
        "references": ["PMLA Section 12", "Income Tax Act Section 269ST"],
    },
    {
        "id": 9,
        "code": "AML-009",
        "name": "Correspondent Banking AML Compliance",
        "framework": "PMLA",
        "description": "Cross-border correspondent banking relationships must have enhanced due diligence and AML programme review.",
        "severity": "high",
        "max_penalty_inr": 5_000_000,
        "penalty_per_day_inr": 20_000,
        "imprisonment_risk": False,
        "ideal_vector_target": {"cross_border_ratio": 0.8, "sector_risk_score": 0.6, "anomaly_risk_score": 0.5},
        "remediation_steps": ["Review correspondent's AML programme", "Obtain board-level approval for relationship", "Perform annual due diligence review"],
        "references": ["PMLA Section 12", "FATF Recommendation 13"],
    },
    {
        "id": 10,
        "code": "AML-010",
        "name": "Virtual Asset / Crypto Transaction Reporting",
        "framework": "PMLA",
        "description": "Virtual digital asset transactions must be reported and VDA service providers must register with FIU-IND.",
        "severity": "high",
        "max_penalty_inr": 2_000_000,
        "penalty_per_day_inr": 10_000,
        "imprisonment_risk": False,
        "ideal_vector_target": {"sector_risk_score": 0.9, "anomaly_risk_score": 0.8, "monthly_txn_volume": 0.6},
        "remediation_steps": ["Ensure VDA provider is registered with FIU-IND", "Report all crypto transactions above threshold", "Maintain KYC for all VDA customers"],
        "references": ["PMLA (Amendment) 2023", "FIU-IND VDA Guidelines"],
    },
    # ═══════════════════════════════════════════════════════════════
    # KYC (Know Your Customer) — RBI Master Direction 2016 — 8 rules
    # ═══════════════════════════════════════════════════════════════
    {
        "id": 11,
        "code": "KYC-001",
        "name": "UBO Declaration",
        "framework": "RBI_KYC",
        "description": "Ultimate Beneficial Ownership must be declared for all legal entities. UBO is any individual holding >25% ownership or control.",
        "severity": "medium",
        "max_penalty_inr": 1_000_000,
        "penalty_per_day_inr": 5_000,
        "imprisonment_risk": False,
        "ideal_vector_target": {"business_age_years": 0.3, "director_count": 0.8, "sector_risk_score": 0.5},
        "remediation_steps": ["Obtain UBO declaration form from entity", "Verify identity of all beneficial owners", "Record ownership structure up to 25% threshold", "Update every 2 years"],
        "references": ["RBI KYC Master Direction 2016, Section 26", "Companies Act 2013, Section 90"],
    },
    {
        "id": 12,
        "code": "KYC-002",
        "name": "PEP Screening",
        "framework": "RBI_KYC",
        "description": "Politically Exposed Persons require Enhanced Due Diligence (EDD). Family members and close associates also covered.",
        "severity": "high",
        "max_penalty_inr": 5_000_000,
        "penalty_per_day_inr": 10_000,
        "imprisonment_risk": False,
        "ideal_vector_target": {"cross_border_ratio": 0.5, "anomaly_risk_score": 0.6, "sector_risk_score": 0.6},
        "remediation_steps": ["Screen all directors against PEP database", "Obtain senior management approval for PEP relationship", "Establish source of wealth/funds", "Conduct enhanced ongoing monitoring"],
        "references": ["RBI KYC Master Direction 2016, Section 27", "FATF Recommendation 12"],
    },
    {
        "id": 13,
        "code": "KYC-003",
        "name": "Periodic KYC Update",
        "framework": "RBI_KYC",
        "description": "High-risk customers require KYC update every 2 years. Medium-risk every 8 years. Low-risk every 10 years.",
        "severity": "low",
        "max_penalty_inr": 500_000,
        "penalty_per_day_inr": 1_000,
        "imprisonment_risk": False,
        "ideal_vector_target": {"business_age_years": 0.9, "sector_risk_score": 0.8, "anomaly_risk_score": 0.3},
        "remediation_steps": ["Schedule KYC update based on risk category", "Collect updated documents", "Verify changes in customer profile", "Refresh risk assessment"],
        "references": ["RBI KYC Master Direction 2016, Section 29"],
    },
    {
        "id": 14,
        "code": "KYC-004",
        "name": "Customer Due Diligence (CDD)",
        "framework": "RBI_KYC",
        "description": "Basic CDD required for all customers: verified identity, address, photograph, and PAN/official ID.",
        "severity": "medium",
        "max_penalty_inr": 1_000_000,
        "penalty_per_day_inr": 5_000,
        "imprisonment_risk": False,
        "ideal_vector_target": {"business_age_years": 0.4, "director_count": 0.5, "sector_risk_score": 0.4},
        "remediation_steps": ["Collect certified copy of identity proof (PAN/Aadhaar)", "Verify address proof", "Capture photograph", "Check against UN sanctions list"],
        "references": ["RBI KYC Master Direction 2016, Section 20-25"],
    },
    {
        "id": 15,
        "code": "KYC-005",
        "name": "Enhanced Due Diligence (EDD)",
        "framework": "RBI_KYC",
        "description": "EDD required for high-risk customers, trust/nominee accounts, and NRI accounts.",
        "severity": "high",
        "max_penalty_inr": 2_000_000,
        "penalty_per_day_inr": 10_000,
        "imprisonment_risk": False,
        "ideal_vector_target": {"cross_border_ratio": 0.6, "anomaly_risk_score": 0.7, "sector_risk_score": 0.8},
        "remediation_steps": ["Obtain additional identity documents", "Verify source of funds/wealth", "Establish purpose of account", "Conduct periodic reviews every 6 months"],
        "references": ["RBI KYC Master Direction 2016, Section 27"],
    },
    {
        "id": 16,
        "code": "KYC-006",
        "name": "Non-Face-to-Face Customer Verification",
        "framework": "RBI_KYC",
        "description": "Digital KYC using Video Customer Identification Process (VCIP) requires specific compliance controls.",
        "severity": "medium",
        "max_penalty_inr": 500_000,
        "penalty_per_day_inr": 2_000,
        "imprisonment_risk": False,
        "ideal_vector_target": {"monthly_txn_volume": 0.5, "cross_border_ratio": 0.3, "business_age_years": 0.2},
        "remediation_steps": ["Use RBI-approved VCIP provider", "Record video with geotag and timestamp", "Verify live photo with PAN/Aadhaar", "Store video recording as per retention policy"],
        "references": ["RBI KYC Master Direction 2016, Section 24A", "RBI Circular on VCIP 2021"],
    },
    {
        "id": 17,
        "code": "KYC-007",
        "name": "Ongoing Monitoring of Transactions",
        "framework": "RBI_KYC",
        "description": "Accounts must be monitored regularly. Transaction patterns inconsistent with customer profile must be investigated.",
        "severity": "medium",
        "max_penalty_inr": 1_000_000,
        "penalty_per_day_inr": 3_000,
        "imprisonment_risk": False,
        "ideal_vector_target": {"monthly_txn_volume": 0.7, "anomaly_risk_score": 0.6, "cash_ratio": 0.5},
        "remediation_steps": ["Set transaction monitoring rules per risk profile", "Review alerts within defined TAT", "Document investigation results", "Escalate unusual patterns to compliance officer"],
        "references": ["RBI KYC Master Direction 2016, Section 30"],
    },
    {
        "id": 18,
        "code": "KYC-008",
        "name": "Record Keeping Requirements",
        "framework": "RBI_KYC",
        "description": "All KYC records must be maintained for 5 years after account closure. Transaction records for 5 years.",
        "severity": "low",
        "max_penalty_inr": 200_000,
        "penalty_per_day_inr": 500,
        "imprisonment_risk": False,
        "ideal_vector_target": {"business_age_years": 0.7, "director_count": 0.3, "sector_risk_score": 0.2},
        "remediation_steps": ["Implement document management system", "Tag all records with retention date", "Conduct annual record audit", "Dispose securely after retention period"],
        "references": ["RBI KYC Master Direction 2016, Section 41", "PMLA Section 12"],
    },
    # ═══════════════════════════════════════════════════════════════
    # GST (Goods and Services Tax) — GST Act 2017 — 6 rules
    # ═══════════════════════════════════════════════════════════════
    {
        "id": 19,
        "code": "GST-001",
        "name": "GST Return Filing Timeliness",
        "framework": "GST",
        "description": "GSTR-1 (monthly/quarterly) and GSTR-3B (monthly) must be filed by prescribed due dates.",
        "severity": "low",
        "max_penalty_inr": 500_000,
        "penalty_per_day_inr": 200,
        "imprisonment_risk": False,
        "ideal_vector_target": {"late_payment_rate": 0.8, "business_age_years": 0.2, "monthly_txn_volume": 0.4},
        "remediation_steps": ["File all pending returns immediately", "Pay late fee (₹50/day SGST + ₹50/day CGST)", "Set up automated return reminders", "Consider GST practitioner engagement"],
        "references": ["GST Act 2017, Section 37-39", "GST Rules 2017, Rule 59-61"],
    },
    {
        "id": 20,
        "code": "GST-002",
        "name": "Invoice Mismatch / Fake ITC",
        "framework": "GST",
        "description": "Input Tax Credit mismatch between GSTR-2A/2B (auto-drafted) and books of accounts indicates fake invoicing.",
        "severity": "critical",
        "max_penalty_inr": 10_000_000,
        "penalty_per_day_inr": 20_000,
        "imprisonment_risk": True,
        "imprisonment_months": 60,
        "ideal_vector_target": {"anomaly_risk_score": 0.8, "monthly_txn_volume": 0.7, "avg_ticket_size": 0.6},
        "remediation_steps": ["Reconcile GSTR-2A/2B with purchase register monthly", "Reverse ineligible ITC with interest", "File amended returns if required", "Report fake suppliers to GSTN"],
        "references": ["GST Act 2017, Section 16", "GST Act 2017, Section 74"],
    },
    {
        "id": 21,
        "code": "GST-003",
        "name": "E-Way Bill Compliance",
        "framework": "GST",
        "description": "E-way bill required for movement of goods exceeding ₹50,000 in value. Must be generated before dispatch.",
        "severity": "medium",
        "max_penalty_inr": 200_000,
        "penalty_per_day_inr": 0,
        "imprisonment_risk": False,
        "ideal_vector_target": {"monthly_txn_volume": 0.6, "avg_ticket_size": 0.7, "cash_ratio": 0.3},
        "remediation_steps": ["Ensure e-way bill generated before every goods movement", "Validate e-way bill validity period", "Train dispatch team on e-way bill rules", "Conduct monthly e-way bill audit"],
        "references": ["GST Act 2017, Section 68", "GST Rules 2017, Rule 138"],
    },
    {
        "id": 22,
        "code": "GST-004",
        "name": "Reverse Charge Mechanism (RCM)",
        "framework": "GST",
        "description": "RCM applies on specified supplies (e.g., unregistered supplier, import of services). Recipient must self-invoice and pay tax.",
        "severity": "medium",
        "max_penalty_inr": 500_000,
        "penalty_per_day_inr": 2_000,
        "imprisonment_risk": False,
        "ideal_vector_target": {"cross_border_ratio": 0.5, "avg_ticket_size": 0.6, "sector_risk_score": 0.4},
        "remediation_steps": ["Identify all RCM supplies in the period", "Self-invoice for each RCM supply", "Pay GST under RCM by due date", "Claim ITC of RCM tax paid (if eligible)"],
        "references": ["GST Act 2017, Section 9(3)", "GST Act 2017, Section 9(4)", "Notification on RCM supplies"],
    },
    {
        "id": 23,
        "code": "GST-005",
        "name": "Annual Return Filing (GSTR-9)",
        "framework": "GST",
        "description": "Annual GST return (GSTR-9) must be filed by December 31 of the following financial year.",
        "severity": "low",
        "max_penalty_inr": 200_000,
        "penalty_per_day_inr": 100,
        "imprisonment_risk": False,
        "ideal_vector_target": {"business_age_years": 0.6, "late_payment_rate": 0.5, "monthly_txn_volume": 0.3},
        "remediation_steps": ["Reconcile annual books with GSTR-9", "File GSTR-9C (audit) if turnover exceeds threshold", "Pay any additional tax with interest", "Review ITC claimed vs eligible"],
        "references": ["GST Act 2017, Section 44", "GST Rules 2017, Rule 80"],
    },
    {
        "id": 24,
        "code": "GST-006",
        "name": "E-Invoicing Compliance",
        "framework": "GST",
        "description": "E-invoicing mandatory for businesses with turnover exceeding prescribed threshold. Reported to GSTN in real-time.",
        "severity": "medium",
        "max_penalty_inr": 500_000,
        "penalty_per_day_inr": 2_000,
        "imprisonment_risk": False,
        "ideal_vector_target": {"monthly_txn_volume": 0.7, "avg_ticket_size": 0.5, "business_age_years": 0.5},
        "remediation_steps": ["Register on e-invoice portal (GSTN)", "Integrate accounting software with IRP", "Generate IRN for all B2B invoices", "Verify e-invoice QR code on all invoices"],
        "references": ["GST Act 2017, Rule 48(4)", "Notification No. 13/2020"],
    },
    # ═══════════════════════════════════════════════════════════════
    # FEMA (Foreign Exchange Management Act) 1999 — 5 rules
    # ═══════════════════════════════════════════════════════════════
    {
        "id": 25,
        "code": "FEMA-001",
        "name": "Unregistered Cross-Border Transfers",
        "framework": "FEMA",
        "description": "International transactions require proper purpose codes and must be reported to RBI. Unregistered transfers attract severe penalties.",
        "severity": "high",
        "max_penalty_inr": 3_000_000,
        "penalty_per_day_inr": 5_000,
        "imprisonment_risk": False,
        "ideal_vector_target": {"cross_border_ratio": 0.9, "anomaly_risk_score": 0.7, "avg_ticket_size": 0.6},
        "remediation_steps": ["Obtain proper purpose codes for all remittances", "File with RBI within prescribed timeline", "Pay compounding fees if applicable", "Seek RBI compounding order for past violations"],
        "references": ["FEMA 1999, Section 5", "FEMA 1999, Section 13"],
    },
    {
        "id": 26,
        "code": "FEMA-002",
        "name": "FDI Reporting (FC-GPR Form)",
        "framework": "FEMA",
        "description": "Foreign Direct Investment must be reported to RBI within 30 days of receipt via FC-GPR form and within 30 days of allotment.",
        "severity": "medium",
        "max_penalty_inr": 1_000_000,
        "penalty_per_day_inr": 2_000,
        "imprisonment_risk": False,
        "ideal_vector_target": {"cross_border_ratio": 0.7, "avg_ticket_size": 0.9, "business_age_years": 0.4},
        "remediation_steps": ["File FC-GPR within 30 days of share allotment", "Download FCTRS (Foreign Collaboration Transaction Reporting System) reference", "Submit annual FC-ROI return by July 15"],
        "references": ["FEMA 1999", "RBI Master Direction on FDI 2017"],
    },
    {
        "id": 27,
        "code": "FEMA-003",
        "name": "Export Proceeds Repatriation",
        "framework": "FEMA",
        "description": "Export proceeds must be realised and repatriated to India within 9 months from date of export.",
        "severity": "medium",
        "max_penalty_inr": 500_000,
        "penalty_per_day_inr": 1_000,
        "imprisonment_risk": False,
        "ideal_vector_target": {"cross_border_ratio": 0.8, "monthly_txn_volume": 0.5, "late_payment_rate": 0.6},
        "remediation_steps": ["Track all outstanding export bills", "Follow up with foreign buyers", "Apply for extension from RBI/AD bank if needed", "Report overdue bills to RBI"],
        "references": ["FEMA 1999, Section 8", "RBI Master Direction on Export of Goods and Services"],
    },
    {
        "id": 28,
        "code": "FEMA-004",
        "name": "Overseas Direct Investment (ODI) Reporting",
        "framework": "FEMA",
        "description": "Overseas investments by Indian entities must be reported in Form ODI within 30 days of effecting the investment.",
        "severity": "medium",
        "max_penalty_inr": 1_000_000,
        "penalty_per_day_inr": 2_000,
        "imprisonment_risk": False,
        "ideal_vector_target": {"cross_border_ratio": 0.6, "avg_ticket_size": 0.9, "business_age_years": 0.7},
        "remediation_steps": ["File Form ODI with designated AD bank", "Submit annual performance report of JV/WOS", "Comply with limit on ODI by Indian entities"],
        "references": ["FEMA 1999", "RBI Master Direction on ODI 2022"],
    },
    {
        "id": 29,
        "code": "FEMA-005",
        "name": "External Commercial Borrowings (ECB) Compliance",
        "framework": "FEMA",
        "description": "ECB must comply with RBI framework: minimum maturity period, end-use restrictions, and reporting in Form ECB-2.",
        "severity": "high",
        "max_penalty_inr": 5_000_000,
        "penalty_per_day_inr": 10_000,
        "imprisonment_risk": False,
        "ideal_vector_target": {"cross_border_ratio": 0.5, "avg_ticket_size": 0.9, "sector_risk_score": 0.5, "business_age_years": 0.6},
        "remediation_steps": ["Verify ECB is under automatic or approval route", "Maintain minimum average maturity period (3 years)", "Use ECB funds only for permitted end-uses", "File Form ECB-2 monthly"],
        "references": ["FEMA 1999", "RBI Master Direction on ECB 2022"],
    },
    # ═══════════════════════════════════════════════════════════════
    # Income Tax — IT Act 1961 — 5 rules
    # ═══════════════════════════════════════════════════════════════
    {
        "id": 30,
        "code": "IT-001",
        "name": "Cash Transaction Limit (Section 269ST)",
        "framework": "INCOME_TAX",
        "description": "No person shall receive ₹2 lakh or more in cash from a single person in a single day, in respect of a single transaction, or in respect of transactions relating to one event or occasion.",
        "severity": "high",
        "max_penalty_inr": 200_000,
        "penalty_per_day_inr": 0,
        "imprisonment_risk": False,
        "ideal_vector_target": {"cash_ratio": 0.9, "avg_ticket_size": 0.8, "anomaly_risk_score": 0.5},
        "remediation_steps": ["Prohibit cash receipts above ₹2 lakh", "Implement digital payment infrastructure", "Train staff on Section 269ST limits", "File Form 61A if cash receipts cross threshold"],
        "references": ["Income Tax Act 1961, Section 269ST", "Income Tax Act 1961, Section 271DA"],
    },
    {
        "id": 31,
        "code": "IT-002",
        "name": "TDS Compliance (Tax Deducted at Source)",
        "framework": "INCOME_TAX",
        "description": "Tax must be deducted at prescribed rates on payments (salary, rent, professional fees, contract payments, etc.) and deposited by 7th of next month.",
        "severity": "high",
        "max_penalty_inr": 2_000_000,
        "penalty_per_day_inr": 1_500,
        "imprisonment_risk": False,
        "ideal_vector_target": {"monthly_txn_volume": 0.6, "avg_ticket_size": 0.7, "late_payment_rate": 0.5},
        "remediation_steps": ["File TDS returns quarterly (Form 24Q, 26Q, etc.)", "Deposit TDS by 7th of every month", "Issue TDS certificate (Form 16/16A) to deductees", "Reconcile TDS with Form 26AS"],
        "references": ["Income Tax Act 1961, Section 192-206", "Income Tax Act 1961, Section 234E (late fee)"],
    },
    {
        "id": 32,
        "code": "IT-003",
        "name": "Income Tax Return Filing",
        "framework": "INCOME_TAX",
        "description": "Income tax return must be filed by the due date (July 31 for individuals, October 31 for businesses requiring audit).",
        "severity": "medium",
        "max_penalty_inr": 500_000,
        "penalty_per_day_inr": 0,
        "imprisonment_risk": False,
        "ideal_vector_target": {"business_age_years": 0.5, "late_payment_rate": 0.6, "monthly_txn_volume": 0.4},
        "remediation_steps": ["File ITR before due date to avoid late fee (Section 234F)", "Get accounts audited before filing if turnover exceeds threshold", "Verify pre-filled data on income tax portal", "Report all bank accounts in ITR"],
        "references": ["Income Tax Act 1961, Section 139(1)", "Income Tax Act 1961, Section 234F"],
    },
    {
        "id": 33,
        "code": "IT-004",
        "name": "Tax Audit Applicability",
        "framework": "INCOME_TAX",
        "description": "Tax audit (Section 44AB) required for businesses with turnover exceeding ₹1 crore (₹10 crore if cash receipts ≤5%) and professionals with gross receipts exceeding ₹50 lakh.",
        "severity": "medium",
        "max_penalty_inr": 500_000,
        "penalty_per_day_inr": 0,
        "imprisonment_risk": False,
        "ideal_vector_target": {"monthly_txn_volume": 0.8, "avg_ticket_size": 0.6, "cash_ratio": 0.5},
        "remediation_steps": ["Appoint a chartered accountant for tax audit", "File tax audit report (Form 3CA/3CB) by October 31", "Prepare audit trail and documentation", "Disclose all transactions accurately"],
        "references": ["Income Tax Act 1961, Section 44AB", "Income Tax Act 1961, Section 271B (penalty)"],
    },
    {
        "id": 34,
        "code": "IT-005",
        "name": "Undisclosed Foreign Income and Assets",
        "framework": "INCOME_TAX",
        "description": "Foreign income and assets must be disclosed in ITR. Non-disclosure attracts 100% tax on undisclosed income and prosecution.",
        "severity": "critical",
        "max_penalty_inr": 10_000_000,
        "penalty_per_day_inr": 0,
        "imprisonment_risk": True,
        "imprisonment_months": 120,
        "ideal_vector_target": {"cross_border_ratio": 0.9, "anomaly_risk_score": 0.8, "avg_ticket_size": 0.7},
        "remediation_steps": ["Disclose all foreign assets in Schedule FA of ITR", "Report foreign income under appropriate head", "File under Black Money Act if applicable", "Consider voluntary disclosure to avoid prosecution"],
        "references": ["Black Money (Undisclosed Foreign Income and Assets) Act 2015", "Income Tax Act 1961, Section 139(1)"],
    },
    # ═══════════════════════════════════════════════════════════════
    # Corporate Governance — Companies Act 2013 — 6 rules
    # ═══════════════════════════════════════════════════════════════
    {
        "id": 35,
        "code": "CORP-001",
        "name": "Board Meeting Requirements",
        "framework": "COMPANIES_ACT",
        "description": "Every company must hold minimum 4 board meetings per year with gap not exceeding 120 days between meetings.",
        "severity": "low",
        "max_penalty_inr": 200_000,
        "penalty_per_day_inr": 500,
        "imprisonment_risk": False,
        "ideal_vector_target": {"director_count": 0.6, "business_age_years": 0.4, "sector_risk_score": 0.2},
        "remediation_steps": ["Schedule 4 board meetings at start of year", "Ensure 120-day gap compliance", "Maintain minutes of meetings within 30 days", "File MGT-14 for certain resolutions"],
        "references": ["Companies Act 2013, Section 173", "Companies Act 2013, Section 118 (minutes)"],
    },
    {
        "id": 36,
        "code": "CORP-002",
        "name": "Annual Return Filing (MGT-7/AOC-4)",
        "framework": "COMPANIES_ACT",
        "description": "Annual return (MGT-7) and financial statements (AOC-4) must be filed with ROC within 60 days of AGM.",
        "severity": "medium",
        "max_penalty_inr": 500_000,
        "penalty_per_day_inr": 200,
        "imprisonment_risk": False,
        "ideal_vector_target": {"business_age_years": 0.6, "director_count": 0.5, "monthly_txn_volume": 0.3},
        "remediation_steps": ["Hold AGM within 6 months of financial year end", "File AOC-4 (financial statements) within 30 days of AGM", "File MGT-7 (annual return) within 60 days of AGM", "Pay additional fees for late filing"],
        "references": ["Companies Act 2013, Section 92 (MGT-7)", "Companies Act 2013, Section 137 (AOC-4)"],
    },
    {
        "id": 37,
        "code": "CORP-003",
        "name": "Beneficial Ownership Register",
        "framework": "COMPANIES_ACT",
        "description": "Every company must maintain a register of significant beneficial owners (holding 10%+ shares or significant control). Must file BEN-2.",
        "severity": "medium",
        "max_penalty_inr": 500_000,
        "penalty_per_day_inr": 500,
        "imprisonment_risk": False,
        "ideal_vector_target": {"director_count": 0.7, "business_age_years": 0.5, "sector_risk_score": 0.5},
        "remediation_steps": ["Identify all significant beneficial owners (>10% shares)", "Maintain register in Form BEN-3", "File BEN-2 with ROC within 30 days of identification", "Update register annually"],
        "references": ["Companies Act 2013, Section 90", "Beneficial Ownership Rules 2018"],
    },
    {
        "id": 38,
        "code": "CORP-004",
        "name": "Related Party Transaction Disclosure",
        "framework": "COMPANIES_ACT",
        "description": "All related party transactions must be approved by audit committee/board and disclosed in financial statements.",
        "severity": "high",
        "max_penalty_inr": 5_000_000,
        "penalty_per_day_inr": 5_000,
        "imprisonment_risk": False,
        "ideal_vector_target": {"monthly_txn_volume": 0.5, "avg_ticket_size": 0.8, "director_count": 0.6},
        "remediation_steps": ["Identify all related parties (as per IND AS 24)", "Obtain audit committee approval for RPTs", "Disclose all RPTs in board report (Form AOC-2)", "Ensure arm's length pricing for all RPTs"],
        "references": ["Companies Act 2013, Section 188", "Companies Act 2013, Section 177 (audit committee)"],
    },
    {
        "id": 39,
        "code": "CORP-005",
        "name": "Directors' KYC (DIR-3 KYC)",
        "framework": "COMPANIES_ACT",
        "description": "Every director with DIN must file DIR-3 KYC annually by September 30. Non-filing leads to DIN deactivation.",
        "severity": "low",
        "max_penalty_inr": 100_000,
        "penalty_per_day_inr": 0,
        "imprisonment_risk": False,
        "ideal_vector_target": {"director_count": 0.8, "business_age_years": 0.3, "sector_risk_score": 0.1},
        "remediation_steps": ["File DIR-3 KYC for all directors before September 30", "Update director personal details if changed", "Pay late fee if filing after due date", "Apply for DIN reactivation if deactivated"],
        "references": ["Companies Act 2013", "MCA Notification on DIR-3 KYC"],
    },
    {
        "id": 40,
        "code": "CORP-006",
        "name": "CSR Compliance",
        "framework": "COMPANIES_ACT",
        "description": "Companies with net worth ≥₹500 Cr or turnover ≥₹1,000 Cr or net profit ≥₹5 Cr must spend 2% of average net profit on CSR.",
        "severity": "medium",
        "max_penalty_inr": 1_000_000,
        "penalty_per_day_inr": 0,
        "imprisonment_risk": False,
        "ideal_vector_target": {"business_age_years": 0.8, "avg_ticket_size": 0.9, "monthly_txn_volume": 0.6},
        "remediation_steps": ["Form CSR committee if thresholds met", "Spend 2% of average net profit of 3 preceding years", "File CSR report in board report", "Disclose unspent amount in specified accounts"],
        "references": ["Companies Act 2013, Section 135", "Companies (CSR Policy) Rules 2014"],
    },
]


def get_rules_by_framework(framework: str) -> List[Dict[str, Any]]:
    """Filter rules by regulatory framework code."""
    return [r for r in COMPLIANCE_RULES if r["framework"] == framework]


def get_rule_by_code(code: str) -> Dict[str, Any] | None:
    """Fetch a single rule by its code (e.g. 'AML-001')."""
    for r in COMPLIANCE_RULES:
        if r["code"] == code:
            return r
    return None


def get_rules_by_severity(severity: str) -> List[Dict[str, Any]]:
    """Filter rules by severity level: critical, high, medium, low."""
    return [r for r in COMPLIANCE_RULES if r["severity"] == severity]


def get_rules_summary() -> Dict[str, int]:
    """Get count of rules per framework for dashboard display."""
    summary: Dict[str, int] = {}
    for r in COMPLIANCE_RULES:
        fw = r["framework"]
        summary[fw] = summary.get(fw, 0) + 1
    return summary
