"""init

Revision ID: 540d6b34a443
Revises: 
Create Date: 2026-07-07 22:53:14.398698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '540d6b34a443'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authorities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('court', sa.String(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('neutral_cite', sa.String(), nullable=True),
    sa.Column('reporter_cite', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('bench', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('hash_keccak256', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('billing_ledger',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('credits_delta', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_retention_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('retention_type', sa.String(), nullable=False),
    sa.Column('table_name', sa.String(), nullable=False),
    sa.Column('record_id', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('retention_period_days', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('firms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('gstin', sa.String(), nullable=True),
    sa.Column('pan', sa.String(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('pincode', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clerk_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('wallet_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.CheckConstraint("role in ('lawyer', 'admin', 'paralegal', 'client')", name='users_role_chk'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_clerk_id'), 'users', ['clerk_id'], unique=True)
    op.create_table('billing_accounts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan', sa.String(), nullable=False),
    sa.Column('credits_balance', sa.Integer(), nullable=False),
    sa.Column('renews_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('authority_id', sa.UUID(), nullable=True),
    sa.Column('para_from', sa.Integer(), nullable=True),
    sa.Column('para_to', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=True),
    sa.Column('vector_id', sa.String(), nullable=True),
    sa.Column('statute_tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('has_citation', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['authority_id'], ['authorities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chunks_authority', 'chunks', ['authority_id'], unique=False)
    op.create_index('idx_chunks_statutes', 'chunks', ['statute_tags'], unique=False, postgresql_using='gin')
    op.create_table('matters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_firms',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('joined_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.CheckConstraint("role in ('owner', 'partner', 'associate', 'member', 'intern')", name='user_firms_role_chk'),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'firm_id')
    )
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('matter_id', sa.UUID(), nullable=True),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('filetype', sa.String(), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('ocr_status', sa.String(), nullable=False),
    sa.Column('checksum_sha256', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('queries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('matter_id', sa.UUID(), nullable=True),
    sa.Column('message_encrypted', sa.JSON(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('filters_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.CheckConstraint("mode in ('general','precedent','limitation','draft')", name='queries_mode_chk'),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pii_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('query_id', sa.UUID(), nullable=True),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('pii_type', sa.String(), nullable=False),
    sa.Column('detection_confidence', sa.Numeric(), nullable=False),
    sa.Column('redacted_count', sa.Integer(), nullable=False),
    sa.Column('original_encrypted', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['query_id'], ['queries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('query_id', sa.UUID(), nullable=True),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Numeric(), nullable=True),
    sa.Column('retrieval_set_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['queries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_votes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('agent', sa.String(), nullable=False),
    sa.Column('decision_json', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Numeric(), nullable=False),
    sa.Column('aligned', sa.Boolean(), nullable=True),
    sa.Column('weights_before', sa.JSON(), nullable=True),
    sa.Column('weights_after', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compliance_audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('officer_id', sa.UUID(), nullable=True),
    sa.Column('original_tier', sa.String(), nullable=False),
    sa.Column('overridden_tier', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('reviewed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['officer_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    op.create_table('onchain_proofs',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('merkle_root', sa.String(), nullable=False),
    sa.Column('tx_hash', sa.String(), nullable=False),
    sa.Column('network', sa.String(), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('onchain_proofs')
    op.drop_table('compliance_audit_logs')
    op.drop_table('agent_votes')
    op.drop_table('runs')
    op.drop_table('pii_records')
    op.drop_table('queries')
    op.drop_table('documents')
    op.drop_table('user_firms')
    op.drop_table('matters')
    op.drop_index('idx_chunks_statutes', table_name='chunks', postgresql_using='gin')
    op.drop_index('idx_chunks_authority', table_name='chunks')
    op.drop_table('chunks')
    op.drop_table('billing_accounts')
    op.drop_index(op.f('ix_users_clerk_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('firms')
    op.drop_table('data_retention_logs')
    op.drop_table('billing_ledger')
    op.drop_table('authorities')
    # ### end Alembic commands ###
