from __future__ import annotations

import re
from typing import Any, Dict, List, Optional
import structlog

from app.core.config import get_settings
from app.core.gemma_client import get_llm_client, get_llm_client_or_none, get_llm_model
from app.agents.base import AgentOutput
from app.retrieval.indian_kanoon import search_statute, search as ik_search

log = structlog.get_logger()


class StatuteAgent:
    name = "statute"

    async def run(self, query: str, packs: List[Dict[str, Any]], matter_docs: List[Dict[str, Any]]) -> AgentOutput:
        """
        Analyze statutory provisions and sections relevant to the query.
        Uses Indian Kanoon API as primary real-time source, falls back to
        local indexed packs. Analysis is generated by the configured LLM
        (Gemma via Google AI Studio, or OpenAI).
        """

        log.info("statute_agent.start", query_length=len(query))

        # Extract statute references from the query itself
        query_statutes = self._extract_statutes_from_query(query)

        # ---------------------------------------------------------------
        # PRIMARY SOURCE: Indian Kanoon API (real-time)
        # ---------------------------------------------------------------
        ik_context = await self._fetch_indian_kanoon_context(query, query_statutes)

        # ---------------------------------------------------------------
        # SECONDARY SOURCE: Local indexed packs
        # ---------------------------------------------------------------
        local_context = self._extract_statute_context(packs)

        # Merge contexts (IK takes precedence)
        statute_context = self._merge_contexts(ik_context, local_context)

        # Build comprehensive statutory analysis using LLM
        reasoning = await self._analyze_statutes(query, statute_context, query_statutes, matter_docs)

        # Extract sources and calculate confidence
        sources = self._extract_sources(statute_context)
        confidence = self._calculate_confidence(statute_context, query_statutes, reasoning)

        log.info("statute_agent.complete",
                 confidence=confidence,
                 sources_count=len(sources),
                 statutes_found=len(query_statutes),
                 ik_used=ik_context["available"])

        return AgentOutput(
            reasoning=reasoning,
            sources=sources,
            confidence=confidence
        )

    async def _fetch_indian_kanoon_context(
        self, query: str, query_statutes: List[str]
    ) -> Dict[str, Any]:
        """Fetch statute-related results from Indian Kanoon API."""
        settings = get_settings()
        if not settings.INDIAN_KANOON_API_TOKEN:
            return {"available": False, "statutes": [], "sections": [], "articles": [], "results": []}

        results: List[Dict[str, Any]] = []
        statutes_found: set = set()
        sections_found: set = set()
        articles_found: set = set()

        try:
            # 1. Search by top query statutes
            for statute in query_statutes[:3]:
                section = None
                if statute.startswith("Section "):
                    section = statute
                    continue  # Handled individually
                if statute.startswith("Article "):
                    continue  # Handled individually

                result = await search_statute(statute, max_results=10)
                for r in result.get("results", []):
                    if r not in results:
                        results.append(r)
                    statutes_found.add(statute)

            # 2. Search specific sections individually
            for statute_ref in query_statutes:
                if statute_ref.startswith("Section "):
                    # Search for the full act name + section
                    for act in self._find_act_for_section(statute_ref, query_statutes):
                        result = await search_statute(act, section=statute_ref, max_results=5)
                        for r in result.get("results", []):
                            if r not in results:
                                results.append(r)
                        sections_found.add(statute_ref)
                elif statute_ref.startswith("Article "):
                    result = await search_statute("Constitution of India", section=statute_ref, max_results=5)
                    for r in result.get("results", []):
                        if r not in results:
                            results.append(r)
                    articles_found.add(statute_ref)

            # 3. General query search for broader context
            if len(results) < 5:
                general = await ik_search(query, max_results=10,
                                          doctypes=["supremecourt", "delhi", "bombay"])
                for r in general.get("results", []):
                    if r not in results:
                        results.append(r)

            return {
                "available": True,
                "statutes": list(statutes_found),
                "sections": list(sections_found),
                "articles": list(articles_found),
                "results": results[:20],  # Cap at 20
            }
        except Exception as e:
            log.warning("statute_agent.ik_fetch_failed", error=str(e))
            return {"available": False, "statutes": [], "sections": [], "articles": [], "results": []}

    def _find_act_for_section(self, section_ref: str, query_statutes: List[str]) -> List[str]:
        """Find the act name that contains a given section reference."""
        # Known act mappings: keyed by short code, valued by searchable names
        act_map: Dict[str, List[str]] = {
            "IPC": ["Indian Penal Code", "IPC"],
            "CRPC": ["Code of Criminal Procedure", "CrPC"],
            "CPC": ["Code of Civil Procedure", "CPC"],
            "Evidence Act": ["Indian Evidence Act"],
            "Contract Act": ["Indian Contract Act"],
            "NI Act": ["Negotiable Instruments Act"],
            "Transfer of Property Act": ["Transfer of Property Act"],
            "Companies Act": ["Companies Act"],
        }
        # Build reverse lookup: full name -> aliases
        full_name_to_aliases: Dict[str, List[str]] = {}
        for short_code, aliases in act_map.items():
            for alias in aliases:
                full_name_to_aliases[alias] = aliases
            full_name_to_aliases[short_code] = aliases

        # Check query_statutes for act names (match against both short codes and full names)
        for qs in query_statutes:
            if qs in full_name_to_aliases:
                return full_name_to_aliases[qs]
            # Also fuzzy match: if qs contains any alias
            for alias, aliases in full_name_to_aliases.items():
                if qs.lower() in alias.lower() or alias.lower() in qs.lower():
                    return aliases

        # Default to general search
        return [section_ref]

    def _merge_contexts(self, ik: Dict[str, Any], local: Dict[str, Any]) -> Dict[str, Any]:
        """Merge Indian Kanoon context with local indexed context."""
        all_statutes = list(set(ik.get("statutes", []) + local.get("statutes", [])))
        all_sections = list(set(ik.get("sections", []) + local.get("sections", [])))
        all_articles = list(set(ik.get("articles", []) + local.get("articles", [])))

        ik_results = ik.get("results", [])
        local_packs = local.get("relevant_packs", [])

        return {
            "statutes": all_statutes,
            "sections": all_sections,
            "articles": all_articles,
            "ik_available": ik.get("available", False),
            "results": ik_results,
            "relevant_packs": local_packs,
            "total_statute_references": len(all_statutes) + len(all_sections) + len(all_articles),
        }

    def _extract_statute_context(self, packs: List[Dict[str, Any]]) -> Dict[str, Any]:
        """Extract statute-related information from local retrieval packs."""
        statutes_found: set = set()
        sections_found: set = set()
        articles_found: set = set()
        relevant_packs: List[Dict[str, Any]] = []

        for pack in packs:
            metadata = pack.get("metadata", {})
            statute_tags = metadata.get("statute_tags", [])

            if statute_tags:
                statutes_found.update(statute_tags)
                relevant_packs.append(pack)

            title = pack.get("title", "")
            self._extract_sections_articles(title, sections_found, articles_found)

            for para in pack.get("paras", []):
                para_text = para.get("text", "")
                self._extract_sections_articles(para_text, sections_found, articles_found)

        return {
            "statutes": list(statutes_found),
            "sections": list(sections_found),
            "articles": list(articles_found),
            "relevant_packs": relevant_packs,
            "total_statute_references": len(statutes_found) + len(sections_found) + len(articles_found),
        }

    def _extract_sections_articles(self, text: str, sections: set, articles: set) -> None:
        """Extract section and article references from text."""
        section_patterns = [
            r'Section\s+(\d+[A-Z]?)\s+of\s+([^,\n\.]+)',
            r'[Ss]ection\s+(\d+[A-Z]?)',
            r'Sec\.\s*(\d+[A-Z]?)',
            r'S\.\s*(\d+[A-Z]?)',
        ]
        for pattern in section_patterns:
            matches = re.finditer(pattern, text, re.IGNORECASE)
            for match in matches:
                sections.add(f"Section {match.group(1)}")

        article_patterns = [
            r'Article\s+(\d+[A-Z]?)\s+of\s+([^,\n\.]+)',
            r'[Aa]rticle\s+(\d+[A-Z]?)',
            r'Art\.\s*(\d+[A-Z]?)',
        ]
        for pattern in article_patterns:
            matches = re.finditer(pattern, text, re.IGNORECASE)
            for match in matches:
                articles.add(f"Article {match.group(1)}")

    def _extract_statutes_from_query(self, query: str) -> List[str]:
        """Extract statute references from the user query."""
        statutes = []

        statute_patterns = {
            r'\bIPC\b|\bIndian Penal Code\b': "Indian Penal Code",
            r'\bCrPC\b|\bCode of Criminal Procedure\b': "Code of Criminal Procedure",
            r'\bCPC\b|\bCode of Civil Procedure\b': "Code of Civil Procedure",
            r'\bEvidence Act\b|\bIndian Evidence Act\b': "Indian Evidence Act",
            r'\bContract Act\b|\bIndian Contract Act\b': "Indian Contract Act",
            r'\bConstitution\b|\bIndian Constitution\b': "Constitution of India",
            r'\bNI Act\b|\bNegotiable Instruments Act\b': "Negotiable Instruments Act",
            r'\bTransfer of Property Act\b': "Transfer of Property Act",
            r'\bSale of Goods Act\b': "Sale of Goods Act",
            r'\bPartnership Act\b': "Indian Partnership Act",
            r'\bCompanies Act\b': "Companies Act",
            r'\bArbitration Act\b|\bArbitration and Conciliation Act\b': "Arbitration and Conciliation Act",
        }

        for pattern, statute_name in statute_patterns.items():
            if re.search(pattern, query, re.IGNORECASE):
                statutes.append(statute_name)

        section_matches = re.findall(r'[Ss]ection\s+(\d+[A-Z]?)', query)
        article_matches = re.findall(r'[Aa]rticle\s+(\d+[A-Z]?)', query)

        for section in section_matches:
            statutes.append(f"Section {section}")
        for article in article_matches:
            statutes.append(f"Article {article}")

        return statutes

    async def _analyze_statutes(
        self,
        query: str,
        statute_context: Dict[str, Any],
        query_statutes: List[str],
        matter_docs: List[Dict[str, Any]],
    ) -> str:
        """Perform comprehensive statutory analysis using the configured LLM."""
        settings = get_settings()

        # Check if any LLM is configured
        if not get_llm_client_or_none():
            log.warning("statute_agent.no_llm", message="No LLM API key configured")
            return self._generate_offline_analysis(query, statute_context, query_statutes)

        try:
            client = get_llm_client()
            model = get_llm_model()
        except Exception as e:
            log.error("statute_agent.llm_init_error", error=str(e))
            return self._generate_offline_analysis(query, statute_context, query_statutes)

        # Build rich context for LLM
        context_parts = []

        if statute_context["statutes"]:
            context_parts.append(f"Relevant statutes found: {', '.join(statute_context['statutes'])}")
        if statute_context["sections"]:
            context_parts.append(f"Sections referenced: {', '.join(statute_context['sections'])}")
        if statute_context["articles"]:
            context_parts.append(f"Articles referenced: {', '.join(statute_context['articles'])}")
        if query_statutes:
            context_parts.append(f"Statutes mentioned in query: {', '.join(query_statutes)}")

        # Include Indian Kanoon search results as real evidence
        ik_results = statute_context.get("results", [])
        if ik_results:
            result_lines = []
            for r in ik_results[:5]:
                title = r.get("title", "Unknown")
                excerpt = r.get("excerpt", "")[:200]
                url = r.get("url", "")
                if excerpt:
                    result_lines.append(f"- {title}: {excerpt}...")
                else:
                    result_lines.append(f"- {title} ({url})")
            context_parts.append("\nIndian Kanoon search results:\n" + "\n".join(result_lines))

        context = "\n".join(context_parts) if context_parts else "No specific statutory references found."

        prompt = f"""You are a senior Indian statutory law specialist. Analyze the statutory provisions relevant to this legal query using the provided context from the Indian Kanoon legal database.

User Query: {query}

Statutory Context:
{context}

Provide a focused, authoritative analysis covering:
1. **Applicable Statutes**: Which specific Indian laws/acts apply and why
2. **Relevant Sections/Articles**: Key provisions with exact section numbers and their scope
3. **Interpretation**: How Indian courts have interpreted these provisions
4. **Requirements**: What conditions/elements must be satisfied
5. **Exceptions/Limitations**: Any exceptions or limiting factors under Indian law

Format with proper markdown. Reference specific case law from Indian courts where relevant.
If the Indian Kanoon results contain relevant case citations, incorporate them.
Be precise about section numbers and statutory language. If no clear statutory provisions apply, explain what general legal principles might govern under Indian law."""

        try:
            response = client.chat.completions.create(
                model=model,
                messages=[{"role": "user", "content": prompt}],
                temperature=0.2,
                max_tokens=1000,
            )
            content = response.choices[0].message.content
            return content or "Unable to generate statutory analysis."
        except Exception as e:
            log.error("statute_agent.llm_error", error=str(e))
            return self._generate_offline_analysis(query, statute_context, query_statutes)

    def _extract_sources(self, statute_context: Dict[str, Any]) -> List[Dict[str, Any]]:
        """Extract source authorities from both IK results and local packs."""
        sources = []

        # From Indian Kanoon results
        for result in statute_context.get("results", [])[:5]:
            docid = result.get("docid") or result.get("id")
            if docid:
                sources.append({
                    "authority_id": str(docid),
                    "para_ids": [],
                    "relevance": "statutory_reference",
                    "title": result.get("title", ""),
                    "court": result.get("source", result.get("description", "Indian Kanoon")),
                    "url": result.get("url"),
                })

        # From local packs
        for pack in statute_context.get("relevant_packs", []):
            authority_id = pack.get("authority_id")
            if authority_id:
                para_ids = [p.get("para_id", 0) for p in pack.get("paras", [])]
                sources.append({
                    "authority_id": authority_id,
                    "para_ids": para_ids,
                    "relevance": "statutory_reference",
                    "title": pack.get("title", ""),
                    "court": pack.get("court", ""),
                })
            if len(sources) >= 10:
                break

        return sources

    def _calculate_confidence(
        self, statute_context: Dict[str, Any], query_statutes: List[str], reasoning: str
    ) -> float:
        """Calculate confidence based on statutory coverage and specificity."""
        base_confidence = 0.3

        # Boost if Indian Kanoon data is available (increases reliability)
        if statute_context.get("ik_available", False):
            base_confidence += 0.15

        if statute_context["total_statute_references"] > 0:
            base_confidence += min(0.3, statute_context["total_statute_references"] * 0.1)

        if query_statutes:
            addressed = sum(1 for s in query_statutes if s.lower() in reasoning.lower())
            if query_statutes:
                base_confidence += (addressed / len(query_statutes)) * 0.25

        section_mentions = len(re.findall(r'[Ss]ection\s+\d+', reasoning))
        article_mentions = len(re.findall(r'[Aa]rticle\s+\d+', reasoning))
        base_confidence += min(0.15, (section_mentions + article_mentions) * 0.03)

        if statute_context.get("relevant_packs") or statute_context.get("results"):
            base_confidence += 0.1

        return min(0.95, base_confidence)

    def _generate_offline_analysis(
        self, query: str, statute_context: Dict[str, Any], query_statutes: List[str]
    ) -> str:
        """Generate informative analysis without LLM, using available context."""
        parts = [
            "**STATUTORY ANALYSIS**",
            "",
            f"**Query**: {query[:200] if len(query) > 200 else query}",
            "",
        ]

        if query_statutes:
            parts.extend([
                "**Applicable Statutes:**",
                f"The query references: {', '.join(query_statutes)}",
                "",
            ])

        if statute_context["statutes"]:
            parts.extend([
                "**Relevant Legal Provisions:**",
                f"Found references to: {', '.join(statute_context['statutes'][:5])}",
                "",
            ])

        if statute_context["sections"]:
            parts.extend([
                "**Specific Sections:**",
                f"Key sections: {', '.join(statute_context['sections'][:5])}",
                "",
            ])

        # Include Indian Kanoon titles as evidence
        ik_results = statute_context.get("results", [])
        if ik_results:
            parts.append("**Supporting Authorities (Indian Kanoon):**")
            for r in ik_results[:5]:
                title = r.get("title", "")
                url = r.get("url", "")
                if title:
                    parts.append(f"- {title}")
                    if url:
                        parts.append(f"  {url}")
            parts.append("")

        parts.extend([
            "**Note:** For a full LLM-powered analysis with detailed interpretation,",
            "configure a Gemma provider (Ollama or GEMMA_API_KEY) in your .env file.",
        ])

        return "\n".join(parts)
